name: Node.js CI with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Reponun Checkout Edilmesi
        uses: actions/checkout@v3

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bağımlılıkların Yüklenmesi
        run: npm install

      - name: Uygulamanın Test Edilmesi (placeholder)
        run: echo "Test yok, sadece build"

      - name: Docker Image Build
        run: docker build -t my-node-app .

